# In keeping things simple, this example assumes the epel repo is enabled on each node
---
- name: Ensure nginx is installed and started
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package is present
    yum:
      name: nginx
      state: present

  - name: Ensure latest index.html is present
    copy:
      src: files/index.html
      dest: /usr/share/nginx/html

  - name: Ensure nginx service is started
    service:
      name: nginx
      state: started
