---
- name: Ensure nginx with wsgi is removed
  hosts: web
  become: yes

  tasks:
    - name: Ensure nginx service is stopped
      service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Ensure nginx package is absent
      yum:
        name: nginx
        state: absent

    - name: Ensure uwsgi package is absent
      pip:
        name: uwsgi
        state: absent

    - name: Ensure files created by nginx-simple are absent
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/nginx.conf
        - /usr/share/nginx/html/index.html
