- name: restart sshd
  service:
    name: "{{ common_ssh_service_name }}"
    state: restarted

- name: Reboot
  shell: sleep 2 && reboot
  async: 30
  poll: 0

- name: Wait for instance
  delegate_to: localhost
  become: no
  wait_for:
    port: "{{ ssh_port | default('22') }}"
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    timeout: 500
    delay: 40

- name: restart firewalld
  service:
    name: "{{ firewalld_service }}"
    state: restarted
