# In keeping things simple, this example assumes the epel repo is enabled on each node
---
- name: Ensure nginx is installed and started via role
  hosts: web
  become: yes
  roles:
    - nginx-simple
